pipeline {
    agent any

    tools {
        maven 'Maven 3.8.6'
        jdk 'jdk 17'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/MrRidadev/ENAA-SKills-Application-de-gestion-des-competences-Partie-2-.git'
            }
        }

        stage('Build Apprenant-Service') {
            steps {
                dir('Apprenant-Service') {
                    bat 'mvn clean install -DskipTests'
                }
            }
        }

        stage('Test Apprenant-Service') {
            steps {
                dir('Apprenant-Service') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package Apprenant-Service') {
            steps {
                dir('Apprenant-Service') {
                    bat 'mvn package'
                }
            }
        }

        stage('Archive JAR') {
            steps {
                archiveArtifacts artifacts: 'Apprenant-Service/target/*.jar', fingerprint: true
            }
        }
    }
}
