services:
  # The service name is changed to match your application.properties URL
  mysql-container-enaa:
    image: mysql:8
    container_name: mysql-container-enaa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: enaa_skills_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - enaa-net
    # This block tells Docker how to check if the database is ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  brief-service:
    build: .
    container_name: brief-service
    ports:
      - "8183:8183"
    networks:
      - enaa-net
    # This block now waits for the database to be healthy before starting
    depends_on:
      mysql-container-enaa:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  enaa-net: